CREATE TABLE customer_setting
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    version       BIGINT                                  NOT NULL,
    user_id       BIGINT,
    settings_json JSONB                                   NOT NULL,
    is_deleted    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_customer_setting PRIMARY KEY (id)
);

ALTER TABLE customer_setting
    ADD CONSTRAINT uk_customer_setting_json UNIQUE (user_id);

ALTER TABLE customer_setting
    ADD CONSTRAINT FK_USER_SETTING_USER FOREIGN KEY (user_id) REFERENCES users (id);

DROP TABLE shared_activity_logs CASCADE;

DROP TABLE shared_audit_logs CASCADE;